# Generated by Django 3.1.4 on 2024-05-02 14:18

from django.db import migrations, models
import mysite.models.profile_models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20240429_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default='', upload_to=mysite.models.profile_models.upload_image_to),
        ),
    ]
