# Generated by Django 3.1.4 on 2024-05-02 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_profile_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='img',
            new_name='image',
        ),
    ]
